// src/actionTypes.js
export const FETCH_RECIPES_REQUEST = 'FETCH_RECIPES_REQUEST';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAILURE = 'FETCH_RECIPES_FAILURE';
export const LOGIN_USER = 'LOGIN_USER';

export const FETCH_RECIPE_DETAIL_REQUEST = 'FETCH_RECIPE_DETAIL_REQUEST';
export const FETCH_RECIPE_DETAIL_SUCCESS = 'FETCH_RECIPE_DETAIL_SUCCESS';
export const FETCH_RECIPE_DETAIL_FAILURE = 'FETCH_RECIPE_DETAIL_FAILURE';
export const FETCH_FEATURED_RECIPES_REQUEST = 'FETCH_FEATURED_RECIPES_REQUEST';
export const FETCH_FEATURED_RECIPES_SUCCESS = 'FETCH_FEATURED_RECIPES_SUCCESS';
export const FETCH_FEATURED_RECIPES_FAILURE = 'FETCH_FEATURED_RECIPES_FAILURE';
